name: Paper Tracker

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggers

jobs:
  track-papers:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/firecrawl_automated_whitepaper_tracking

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.15'
          cache: 'pip'

      - name: Verify Directory
        run: |
          pwd
          ls -la
          echo "Current directory structure:"
          tree -L 3

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version

      - name: Install dependencies
        run: |
          poetry install

      - name: Test Database Connection
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: |
          echo "Testing database connection..."
          export PGOPTIONS='-c prefer_ipv4=true'
          echo "$(dig +short db.zhxbejkyincpzcoihpvn.supabase.co | head -n1) db.zhxbejkyincpzcoihpvn.supabase.co" | sudo tee -a /etc/hosts
          
          poetry run python -c "
          import os
          import sys
          print(f'Python version: {sys.version}')
          print(f'Python path: {sys.path}')
          from database import Database
          try:
              print('Attempting database connection...')
              db = Database(os.getenv('POSTGRES_URL'))
              print('Database connection successful!')
              print('Testing simple query...')
              result = db.engine.execute('SELECT 1').scalar()
              print(f'Query result: {result}')
          except Exception as e:
              print(f'Database connection failed: {str(e)}')
              print(f'Error type: {type(e).__name__}')
              print('Error details: ' + str(getattr(e, '__dict__', 'No details available')))
              exit(1)
          "

      - name: Run paper tracker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          export PGOPTIONS='-c prefer_ipv4=true'
          poetry run python firecrawl_crawl_extract.py

      - name: Notify on Failure
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content":"⚠️ Paper Tracker workflow failed! Please check the GitHub Actions logs."}' $DISCORD_WEBHOOK_URL
